---
- name: Update all packages
  hosts: lts_custom_kernel
  gather_facts: false
  become: true
  vars:
  tasks:
    - name: Perform updates on all hosts
      ansible.builtin.dnf:
        name: "*"
        state: latest