---
- name: Remove old 5.14.x kernels
  hosts: lts_custom_kernel
  gather_facts: false
  become: true
  vars:
  tasks:
    - name: Remove old kernels
      ansible.builtin.shell: 'dnf -y remove "kernel*5.14*"'
      register: removal_result
      changed_when: removal_result.stderr != "No packages marked for removal."
